### PR TITLE
bump nosql for postgres support

### PR DESCRIPTION
**Pull request by dopey**

### CODE REVIEW

**Comment by hslatman** [comment]
🎉

**Review by maraino — APPROVED** [review]
LGTM

I was wondering why pgx depends on pq, and it turns out that github.com/jackc/pgtype has a package used in tests that allows running the same tests on both pgx and pq.

**Comment by imZack** [comment]
This is awesome! Can we have a release for enabling pg?

**Comment by dopey** [comment]
👍 released

**Pull request merged**
