### PR TITLE
readme: fix HTTPS definition

### PR DESCRIPTION
**Pull request by emersion**
It's the other way around.

### CODE REVIEW

**Comment by emersion** [comment]
https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html

**Comment by mmalone** [comment]
Hi @emersion. I can understand some wariness around the CLA process, but it really is necessary for projects with a corporate custodian. I had a long conversation with our lawyers about this issue and the consensus is simply that a CLA helps to clarify and create a direct record of the otherwise implicit relationship between contributors and the project custodian (smallstep, in this case). In particular, it provides a consistent explicit record of contributors and their clear intent to make an open source contribution, it clarifies how IP rights like patent are handled, and it provides a mechanism for us to take contributions from employees via an additional corporate CLA.

Regarding re-licensing and/or commercializing, that would be possible regardless — the project is liberal licensed under Apache 2.0, not virally licensed under something like GPL. You (or everyone else) also have that right — this code base is available for use in commercial products under the license terms, regardless of CLA. I believe this is a good and healthy thing, but also understand there are various reasonable perspectives and philosophies around open source.

I’m sorry if our licensing practices are incompatible with your philosophies here. I’m happy to answer any additional questions you may have, and I do encourage you to reconsider. Regardless, thank you for your time and for at least attempting a contribution!

**Comment by ddevault** [comment]
Author of the linked article here. Hundreds of projects with corporate custodians get by fine every day without a CLA. When was the last time you heard of any legal fallout from it? On the other hand, I know of many occasions where contributor rights have been threatened due to CLAs. A CLA is signaling your future intent to close source the software, and doesn't respect your contributors. At best this is CYA taken to an unfortunate extreme.

**Comment by mmalone** [comment]
Thank you for the feedback!

Yea I made the same argument about legal fallout (or lack thereof). I also pointed out that the default GitHub ToS stipulates that all PRs are “in = out” — if you make a contribution it’s licensed the same as the project you contribute to.

On the latter point, lawyers were concerned that 1) the ToS is a legal relationship between GitHub and the contributor, not between smallstep and the contributor, so I wouldn’t have standing in any court (or something) and 2) they were not aware of any case where that aspect of the GitHub ToS had been tested in court.

Re: legal fallout, the issue is not that my company is likely to get sued (you’re right, it’s not). Rather, it’s an issue that is likely to come up in diligence in the future if my company either sells or raises more money. Investors or acquirers will want to ensure that all IP has unambiguous provenance. While legal fallout is extremely unlikely, I’ve been advised that this is the sort of thing that will *definitely* come up in diligence and will *definitely* be problematic if anything non-standard is done. 

So that’s pretty lame... but sometimes you gotta choose your battles. Seeing as the license is already Apache 2.0 there already aren’t really any limitations on commercial use, so I don’t see any big problem with the CLA approach for this project.

CLA definitely isn’t a signal of future intent to close source. At least not in this case. We do plan on having an enterprise version at some point — we haven’t hidden that intent  — but we don’t need a CLA for that. And any version that is open sourced will always be open source (you can’t un-open-source a thing). A huge number of projects are CLA’d these days — kubernetes, Apache, Linkerd, Envoy, and anything else in CNCF of Apache Foundation, for starters. I don’t think it’s fair to say that these projects are all signaling intent to close source...

The other non-CLA option is a DCO. Is that ok with you? If so, what significant differences are there from your perspective?

**Comment by ddevault** [comment]
>Re: legal fallout, the issue is not that my company is likely to get sued (you’re right, it’s not). Rather, it’s an issue that is likely to come up in diligence in the future if my company either sells or raises more money. Investors or acquirers will want to ensure that all IP has unambiguous provenance. While legal fallout is extremely unlikely, I’ve been advised that this is the sort of thing that will definitely come up in diligence and will definitely be problematic if anything non-standard is done.

Right, but none of this matters to your contributors. Some vauge future maybe-will-maybe-won't problem with monetizing this software isn't relevant to the contributor, and in fact may be actively against their interests.

>CLA definitely isn’t a signal of future intent to close source. At least not in this case.

All of that smoke coming from the kitchen isn't a signal that my house is on fire, either.

>The other non-CLA option is a DCO. Is that ok with you? If so, what significant differences are there from your perspective?

DCO is way better. All a DCO says is that they did their due dilligence to make sure they have ownership over the changes they made. Linux has used this to great effect for many years.

**Comment by mmalone** [comment]
Lol well you’re certainly not going to convince me that my intent was anything other than what I know it was :). In terms of open source ecosystem health, it seems like there should be community interest in anything that makes open source development compatible with funding sources. I love open source, but I also need to feed my kids. Contributors wouldn’t have a project to contribute to if there wasn’t a way for me to open sources this stuff while also satisfying fiduciary and other obligations. That said, I certainly respect others’ opinions.

Re: intent to “close source” I’ll repeat — there’s no need for a CLA for that. If the project was GPL’d or something then sure, but under Apache 2 this code can already be forked and sold, or otherwise incorporated into commercial software. Personally, I understand this possibility when I write open source software. That’s my preference. To me, open source means “do whatever you want with this code — it’s for the world”. To me, that includes commercialization. I do find tactics employed by projects like MongoDB — where stuff is GPL’d then copyright assignment is used so that *only* 10gen (or whatever they’re called now) can commercialize — is sneaky and lame. But the liberal license is a pretty clear signal of this project’s position on that matter, and it completely changes the dynamic — anyone can commercialize.

In fact, the only thing a CLA really gives us on top of what liberal license already does is the ability to re-license under a *different* and *incompatible* *open source license* like, say, GPL. That’d be impossible without either a CLA or individual sign-off from every contributor. 🤷‍♂️

**Comment by ddevault** [comment]
>Lol well you’re certainly not going to convince me that my intent was anything other than what I know it was

I don't have to convince you what your intent is - *you* have to convince *everyone else* of your intents. This is hard when there's a big pile of legalese giving you an exit hatch from your smooth talk.

>In terms of open source ecosystem health, it seems like there should be community interest in anything that makes open source development compatible with funding sources. I love open source, but I also need to feed my kids. Contributors wouldn’t have a project to contribute to if there wasn’t a way for me to open sources this stuff while also satisfying fiduciary and other obligations. That said, I certainly respect others’ opinions.

On the whole, I agree with you. However, a CLA is not necessary for this goal. The commitment to open source is more important than monetization, and optimizing for monetization potential is going to alienate contributors. After all, @emersion was never going to see the money. The options a CLA gives you for monetization are things a dying company does to desparately wring out a little more money from straggling businesses that are stuck with its software, Oracle-style, not something a healthy project would consider.

>Re: intent to “close source” I’ll repeat — there’s no need for a CLA for that. If the project was GPL’d or something then sure, but under Apache 2 this code can already be forked and sold, or otherwise incorporated into commercial software. Personally, I understand this possibility when I write open source software. That’s my preference. To me, open source means “do whatever you want with this code — it’s for the world”. To me, that includes commercialization. I do find tactics employed by projects like MongoDB — where stuff is GPL’d then copyright assignment is used so that only 10gen (or whatever they’re called now) can commercialize — is sneaky and lame. But the liberal license is a pretty clear signal of this project’s position on that matter, and it completely changes the dynamic — anyone can commercialize.

I'm not saying commercialization is bad or that anyone couldn't fork this library and make it closed source. The catch is that they'd still be bound by the terms of the Apache 2.0 license, which protects the rights of users, contributors, and maintainers. The Apache license protects more rights than you may expect. However, you're right - you *can* make a closed source fork if you want to. So why do you have a CLA?

**Comment by mmalone** [comment]
> I don't have to convince you what your intent is - you have to convince everyone else of your intents. This is hard when there's a big pile of legalese giving you an exit hatch from your smooth talk.

All I can do is use my words, as I’m doing, to explain my thinking. If you don’t believe me that sucks for me, but it’s your prerogative. I’m sorry that explaining my position has come across as “smooth talk”. I value transparency. That’s why I chose to respond here instead of ignoring the issue.

> The options a CLA gives you for monetization are things a dying company does to desparately wring out a little more money from straggling businesses that are stuck with its software

The options for me here were 1) don’t open source or 2) open source in a way that’s compatible with my obligations to investors, employees, customers, and other business stakeholders. I chose option two, and I’m not sorry for that.

There’s no hidden agenda here. I’ve already said we plan on having an enterprise version of this product. CLA changes nothing. Even if we re-licensed, the existing code base would continue to be available under the old license forever, so it would only impact new code and contributions. It’d be literally the same thing as a commercial version of a liberal licensed project, modulo some fine print. You could even fork the code base and keep it Apache 2.0.

> The Apache license protects more rights than you may expect. However, you're right - you can make a closed source fork if you want to. So why do you have a CLA?

As far as I know there are no rights that are lost due to the CLA. I have read Apache 2.0, the individual CLA, and the corporate CLA.

Again, the reason we have a CLA is because my lawyers advised that having an explicit affirmation from contributors that they agree to the open source license terms is best practice for good governance, so that all IP has clear provenance. Further, CLA provides a mechanism for taking contribution from employees of other companies via a corporate CLA (DCO doesn’t have a corporate sign-off mechanism and doesn’t include an explicit patent provision). That’s it.

**Comment by ddevault** [comment]
>All I can do is use my words, as I’m doing, to explain my thinking.

Yes, but you're using these words too:

https://cla-assistant.io/smallstep/certificates?pullRequest=15

You do your thing, dude. But I will discourage people from using or contributing to your project.

**Comment by mmalone** [comment]
That’s pretty spiteful, but cool. Do you do the same for CNCF, most (all?) Linux Foundation projects, Google, Facebook, Go, Python, Django, Puppet, and every other company and project that uses a CLA?

I’m legitimately interested in a good reason why we shouldn’t be using a CLA. Like, actually and honestly interested. I have not heard one yet. I’ve given you several good and valid reasons explaining why we’re using a CLA, and all I’ve gotten back is FUD. CLAs are incredibly common and considered good practice for governance. I remain unconvinced, for now.

**Comment by ddevault** [comment]
Linux uses a DCO, which we already discussed. You seemed open to that before, in fact. What changed? And yes, I discourage people from contributing to those projects.

>I’m legitimately interested in a good reason why we shouldn’t be using a CLA.

I've given my reasons excruciatingly clearly. At this point I think you've wrapped yourself up in a comfortable shell of cognitive dissonance so your worldview isn't threatened.

**Comment by mmalone** [comment]
I’m open to DCO but I don’t think it matters much since Apache 2.0 is only re-affirming the existing relationship and the only new and useful right we’d potentially get is the ability to re-license the project under a different open source license... which would basically only be GPL. CLA might be more dangerous in other contexts, but I just don’t see the danger here.

The main reason to *not* do DCO is that it’s harder to take corporate contributions.

Your argument so far against CLA is that bad actors could hypothetically do evil stuff that wouldn’t be prevented by not having a CLA... So if the CLA/no CLA distinction doesn’t change the ability to do evil stuff, but having a CLA has some clear benefits w.r.t. IP provenance, why not have a CLA?

I respect your right to fight for what you believe in. Keep fighting the good fight! I really don’t have a huge vested interest here in anything other than good governance and something that satisfies as many people as possible — users, contributors, investors, etc. Unfortunately, it’s sometimes not possible to satisfy everyone.

**Comment by ddevault** [comment]
>The main reason to not do DCO is that it’s harder to take corporate contributions.

Hundreds of companies contribute to the Linux kernel every day.

I'm not going to repeat myself to address your other points.

**Comment by mmalone** [comment]
This project is not the Linux kernel. The Linux kernel can do whatever it wants and will continue to be used, funded, and take contributions.

I might take a closer look at DCO at some point to see if we can make it work, but right now we’re focused on feature work. Thanks again for your time!

**Pull request closed without merging**
