### PR TITLE
scep: minor cleanup

### PR DESCRIPTION
**Pull request by azazeal**
This PR soups up `scep` & `scep/api` a bit by:

- removing `scep.Error`.
- refactoring to export less functionality.
- eliminating `scep`'s dependency to `pkg/errors`

### CODE REVIEW

**Review by maraino — APPROVED** [review]
LGTM, @hslatman owns this code, so he should have the last word on it.

One thing that I noticed, not related to this PR, is that `CreateFailureResponse` should not be part of authority, the authority should provide a signer that we can use to create the proper message.

**Review by hslatman — APPROVED** [review]

**Comment by hslatman** [comment]
The changes so far look OK. Did a quick test with a SCEP client and it still reacts as before. As discussed, I want to get back to this functionality to add tests, so that further refactoring becomes easier.

**Comment by maraino** [comment]
@hslatman ok, I saw Auth and assumed the `authority` package.

**Comment by hslatman** [comment]
No problem. It's not the cleanest code.

I can probably remove that interface in the near future. I'm not doing any mocking ATM anyway 😅. Creating an actual instance for testing is better IMO, so I'll do that when I can spend some time on this part again.

**Comment by azazeal** [comment]
> No problem. It's not the cleanest code.
> 
> I can probably remove that interface in the near future. I'm not doing any mocking ATM anyway 😅. Creating an actual instance for testing is better IMO, so I'll do that when I can spend some time on this part again.

I can take out the interface for you if you'd like - let's take this offline.

**Pull request merged**
