### PR TITLE
Added Resolver Option

### PR DESCRIPTION
**Pull request by 256dpi**
Implementation of the feature requested in #171.

### CODE REVIEW

**Comment by maraino** [comment]
@256dpi Thanks for the PR, we'll merge it, but can you fix the gofmt issue in the app.go

**Comment by maraino** [comment]
The linter error is:
```
commands/app.go:34: File is not `gofmt`-ed with `-s` (gofmt)
```

**Comment by maraino** [comment]
@256dpi I'll merge it and fix the error.

**Comment by 256dpi** [comment]
@maraino Thanks!

**Pull request merged**
