### PR TITLE
Support CSR Requests from PKCS11

### PR DESCRIPTION
**Pull request by gdbelvin**
This PR 
- Slightly simplifies the command line flags to make them
  - Positive statements which are easier to reason about
  - Remove duplicate flag `RootOnly` which was unclear
 - Adds a `GenerateRoot` flag to support not generating a root -> create CSR
 - Implements CSR signing

### CODE REVIEW

**Comment by maraino** [comment]
I'm making some changes in your branch, I'll let you check them before merging this.

**Comment by maraino** [comment]
@gdbelvin Take a look to https://github.com/smallstep/certificates/pull/741/commits/febb6198823b070f1d26e9e8c6207b4a1c5a8d97 and let me know if you're ok with it.

**Review by maraino — APPROVED** [review]
@gdbelvin I've made some changes (febb619), let me know if you're ok with them

**Comment by gdbelvin** [comment]
LGTM

**Comment by maraino** [comment]
👍

**Pull request merged**
