### PR TITLE
PKCS11 Init Pin Flag

### PR DESCRIPTION
**Pull request by gdbelvin**
Adds a "pin" flag to cmd/step-pkcs11-init so that it can take it as input from another program

### CODE REVIEW

**Comment by maraino** [comment]
@gdbelvin I don't think this is actually doing anything, if the pin in the `--kms` URI is not set it will always ask for one.

You can pass a pin with the parameters `pin-value` or `pin-source` like this:
```sh
step-pkcs11-init --kms 'pkcs11:module-path=/usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so;token=YubiHSM?pin-value=0001password'
# or 
step-pkcs11-init --kms 'pkcs11:module-path=/usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so;token=YubiHSM?pin-source=/tmp/password.txt'
```

**Comment by maraino** [comment]
This URI is based on the [RFC7515](https://tools.ietf.org/html/rfc7512)

**Comment by gdbelvin** [comment]
Thanks for pointing this out

**Comment by maraino** [comment]
Right now pin source must be a text file with the pin in it

**Comment by maraino** [comment]
Changing your PR to actually work is just one extra condition here 
https://github.com/smallstep/certificates/blob/9146fe8055d2132ee4133143e2265e0c44d7f7eb/cmd/step-pkcs11-init/main.go#L121

**Comment by gdbelvin** [comment]
Thanks, like this?

**Review by maraino — APPROVED** [review]
That looks good Gary.

**Pull request merged**
