### PR TITLE
add AuthParams to OIDC struct

### PR DESCRIPTION
**Pull request by jdoupe**
#### Name of feature:

Add "AuthParams" to OIDC provisioner.

#### Pain or issue this feature alleviates:

AuthParams (or "extra parameters for the authorization request") are sometimes a requirement for OIDC configurations.  Someone had already added the capability as a command line parameter, but remote requests to a CA wouldn't be able to include any extra parameters.

#### Is there documentation on how to use this feature? If so, where?

Not absolutely sure where to update this, but it would entail the addition of an "authParams" key within an OIDC provisioner:
e.g.
```
                               "authParams": [
                                        "myextrakey=myextravalue"
                                ],
```

#### Supporting links/other PRs/issues:

💔Thank you!

### CODE REVIEW

**Comment by maraino** [comment]
Hi @jdoupe, 

We will accept this contribution and https://github.com/smallstep/cli/pull/1150, but they are not a complete PR as it does not allow configuring the provisioners in a database and a linked CA.

I've added the details for this in a similar PR, see https://github.com/smallstep/certificates/pull/1796#issuecomment-2059739628

And we will work on this, but it can take some time, you can also send us a more complete PR.

**Comment by maraino** [comment]
Similar to the other PR, the workaround is adding `"auth-param" to the defaults.json so it sets those flags automatically.

**Comment by jdoupe** [comment]
@maraino,

Thanks for the feedback!

I've updated my branch here to include "Scopes" from https://github.com/smallstep/certificates/pull/1796 along with the linkedca provisioner bits.  And to that end, I also created a branch on smallstep/linkedca to address the proto changes.
(https://github.com/jdoupe/linkedca/tree/AuthParams).

I'll submit a PR for that when I get around to seeing if I can test the database and linked ca scenarios.

I also created a

**Comment by jdoupe** [comment]
Confirmed functionality in "Remote Provisioner Management" configuration.

**Comment by jdoupe** [comment]
Linking related PR's for reference:
https://github.com/smallstep/linkedca/pull/84
https://github.com/smallstep/cli/pull/1154

**Review by maraino — APPROVED** [review]
Thanks @jdoupe, I will upgrade the linkedca dependency and merge.

**Pull request merged**
