### PR TITLE
Dockerfile for HSM-enabled Step CA

### PR DESCRIPTION
**Pull request by jschlyter**
### Description

- Update existing Dockerfile to include GCP and AWS KMS (does not require CGO)
- Add new Dockerfile to build Step CA with support for PKCS#11 and Yubikey (with CGO and PCSC), not yet included in the build process 
- Start pcscd in entrypoint if installed

### CODE REVIEW

**Comment by tashian** [comment]
Hi Jakob,
Thanks for the PR!
I was able to get both images to build in my local environment.
I'm wondering if there's a way we can achieve this CGO-enabled build without duplicating the Dockerfile?
For example, using a build arg and some sort of conditional.

**Comment by maraino** [comment]
@jschlyter Nice, have you tested pkcs#11 or yubikey with musl?

**Comment by jschlyter** [comment]
> @jschlyter Nice, have you tested pkcs#11 or yubikey with musl?

I've tested it with SoftHSM, but not with Yubikey PIV.

**Comment by jschlyter** [comment]
> I'm wondering if there's a way we can achieve this CGO-enabled build without duplicating the Dockerfile and adding 3-4 lines? It would be nice if we didn't have two Dockerfiles. Maybe we could use a build arg and some sort of conditional.

It's not pretty, but it could be done like this: https://gist.github.com/jschlyter/ed4196eb4b907b0ab3448cdca0a6d939

The problem is that Docker doesn't really have conditionals and every command must succeed.

**Comment by tashian** [comment]
Ok, I'm comfortable with having a second Dockerfile, in that case.

**Review by tashian — APPROVED** [review]
lgtm!

**Pull request merged**
