### PR TITLE
KMS URI configuration

### PR DESCRIPTION
**Pull request by maraino**
### Description

This PR adds support to configure cloudkms, awskms, and YubiKey using a URI.

### CODE REVIEW

**Comment by tashian** [comment]
Just curious about this, I have seen the `pkcs11:` URI scheme before. Any any of these URI schemes & parameters standardized, or is this specific to configuring `step-ca`?

**Comment by tashian** [comment]
I noticed [this Apache Camel config page](https://camel.apache.org/components/3.8.x/aws-kms-component.html) refers to an `aws-kms` scheme

**Review by dopey — APPROVED** [review]
lgtm

**Comment by maraino** [comment]
> Just curious about this, I have seen the `pkcs11:` URI scheme before. Any any of these URI schemes & parameters standardized, or is this specific to configuring `step-ca`?

It's based on https://tools.ietf.org/html/rfc7512

**Pull request merged**
