### PR TITLE
document breakout from step to step-cli

### PR DESCRIPTION
**Pull request by nimbius**
### Description
Hi Smallstep
It looks like you're breaking the binaries out into step-cli and step-ca, so i updated to readme to reflect this change.  

💔Thank you!

### CODE REVIEW

**Comment by nimbius** [comment]
ugh, nevermind.  I have to grant CLA assistant access to my entire account for just six lines of code? no thanks.

please update your documentation when you get a chance.

**Comment by dcow** [comment]
@nimbius CLAassistant is an OAuth application with a sole permission allowing read-only access to your email address. You do not grant it access to your entire account.

**Comment by dopey** [comment]
Also, while we're calling the `step` CLI package `step-cli`, the actual name of the executable is `step`. The naming is confusing for sure. I think we originally decided to call the package `step-cli` because debian had an existing package called `step`.

So, for the most part, I think the documentation that you are referring to is actually correct. Just, maybe, a bit confusing. If you have any suggestions on how we can make that less confusing, we definitely want to hear them.

**Comment by mmalone** [comment]
Couple things...

First, it looks like this might not be a docs problem, but a packaging one. The canonical name of the binary is actually `step`, not `step-cli`. Some of our packages I think install as `step-cli` and symlink `step` to that. I’m not sure why we’re doing that but, regardless, the canonical name is `step` and that’s the name used in all our docs and blog posts and whatnot. If it’s not possible to update the arch linux package for some reason we should probably just note that the binary name is different for that distribution in the install notes, rather than changing the binary name everywhere. Ideally we change or symlink the binary though.

Second, I understand your frustration with CLA assistant. We’ve had this come up before and, for minor stuff like this, we can accept without you agreeing to the CLA. But it is easier for us, from a governance perspective, if you do agree to the CLA. As @dcow said, it doesn’t really get much “access”, it just needs you to authenticate. But I get it if you really don’t want to.

Thanks for your help!

**Comment by nimbius** [comment]
@dopey 
if it helps, i think renaming the cli might be a good idea.  Arch has step as a package as well :(
'step ca' and 'step-ca' initially are a pretty confusing pair of commands.  maybe stepctl/stepcli  and stepd?  Assuming Lennart isnt using it.  It should try to be consistent across all platforms for folks provisioning debian from arch or vice versa.  If there isnt a systemd service file for step-ca id like to contribute one as well.

@mmalone 
CLA is a 21st century devil we know i guess. Every company wants to make sure they have the rights to properly handle thorny issues like redistribution or DMCA.  its OT, but worth mentioning.  The off-putting part of the two step connection is this screen in particular, when CLA Assistant goes for more access:

auth_screen2

_write_ access to my gists, commit statuses, webhooks and services? for something that isnt even in my CI chain?

**Comment by maraino** [comment]
Weird, I do cla-assistant.io only asks me for the `Personal user data - Email address (read-only)`.

**Comment by dcow** [comment]
@nimbius woah I see the same thing now, too, when visiting https://cla-assistant.io/. I wouldn't grant CLA assistant those permissions just for signing something, either. When I've used it previously, I only needed to grant email read access and that's the extent of my current permissions grant:

cla-assistant

Curious, if you click this link: https://cla-assistant.io/smallstep/certificates?pullRequest=251 are you still asked to grant it all those permissions, or does it just ask you for read-only access to your email? I wonder if this is a discrepancy between signing in through their main site with the (presumed) intention to setup an integration (which would need those additional permissions) vs simply trying to view an arbitrary CLA which should only need an identifier for your signature.

**Comment by nimbius** [comment]
@dcow yep, same condition.  The service wants an integration, which frankly for confirming the CLA seems a touch heavy handed for a one-time sig?  nbd though since its just read-public-stuff.  Its the second screen that starts asking for not-so-public stuff.

**Comment by dcow** [comment]
@nimbius I've opened an issue with CLA assistent: https://github.com/cla-assistant/cla-assistant/issues/566. Like @mmalone said, we're happy to accept your contributions irrespective of whether you're ultimately able to sign using cla-assistent or not. 

Re: systemd, please use https://github.com/smallstep/certificates/issues/122 to discuss. I'll can add an update later about where we are in our current thought process, but we'd love to hear any suggestions you have over there so we can kick off some fresh discussion.

**Comment by dcow** [comment]
@nimbius according to https://github.com/cla-assistant/cla-assistant/issues/566 the issue is indeed the route used to access cla-assistant's services. Please double check that you're using this link:

 https://cla-assistant.io/smallstep/certificates?pullRequest=251

to access the CLA. You should not be prompted for additional permissions beyond email read access.

**Pull request closed without merging**
